<?php
return[
    'ARTICLE_REFERER_URL'=>'/bbs/article/',
    'ARTICLE_ENTRY_REFERER_URL'=>'/bbs/article_entry',
    'ARTICLE_LIST_SEARCH_REFERER_URL'=>'/bbs/list',
    'GROUP_CD_ALL'=>0,
    'MAX_CNT_BBS'=>10,
    'GOOGLE_KEY'=>'AIzaSyCmbGg_HjG3_kKzeh4KFBULFghh2GDOYK0'
];
